export const STEP_TYPES = {
    LINE: "LINE",
    VISIT: "VISIT",
    READ_ARRAY: "READ_ARRAY",
    WRITE_ARRAY: "WRITE_ARRAY",
    SWAP: "SWAP",
    COMPARE: "COMPARE",
    CREATE_VARIABLE: "CREATE_VARIABLE",
    ASSIGN_VARIABLE: "ASSIGN_VARIABLE",
};